// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-Zh6wOpxZW-5fG282OCpCSKORonMIHs',
    appId: '1:898556410462:web:aaa514417fe53f09a852cf',
    messagingSenderId: '898556410462',
    projectId: 'smart-notes-app-2a59b',
    authDomain: 'smart-notes-app-2a59b.firebaseapp.com',
    storageBucket: 'smart-notes-app-2a59b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAC5F-2tPcWl1bVDeSzivfhiTrwM7xUo',
    appId: '1:898556410462:android:9f9808cb93a5d639a852cf',
    messagingSenderId: '898556410462',
    projectId: 'smart-notes-app-2a59b',
    storageBucket: 'smart-notes-app-2a59b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpQzynjgIkp3rXlzMDOCET1RufqGXfXM',
    appId: '1:898556410462:ios:c3f3773c9b7a3c7fa852cf',
    messagingSenderId: '898556410462',
    projectId: 'smart-notes-app-2a59b',
    storageBucket: 'smart-notes-app-2a59b.firebasestorage.app',
    iosBundleId: 'com.example.smartNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZpQzynjgIkp3rXlzMDOCET1RufqGXfXM',
    appId: '1:898556410462:ios:c3f3773c9b7a3c7fa852cf',
    messagingSenderId: '898556410462',
    projectId: 'smart-notes-app-2a59b',
    storageBucket: 'smart-notes-app-2a59b.firebasestorage.app',
    iosBundleId: 'com.example.smartNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-Zh6wOpxZW-5fG282OCpCSKORonMIHs',
    appId: '1:898556410462:web:b97cbef1571d69f7a852cf',
    messagingSenderId: '898556410462',
    projectId: 'smart-notes-app-2a59b',
    authDomain: 'smart-notes-app-2a59b.firebaseapp.com',
    storageBucket: 'smart-notes-app-2a59b.firebasestorage.app',
  );
}
